import pandas as pd
import joblib
from Bio.SeqUtils.ProtParam import ProteinAnalysis
import os

def predict_my_strains(model_path, output_csv):
    # 1. Kiểm tra mô hình
    if not os.path.exists(model_path):
        print(f"❌ Lỗi: Không tìm thấy file mô hình tại {model_path}.")
        return

    model = joblib.load(model_path)
    
    # --- DỮ LIỆU 10 CHỦNG (Sử dụng Triple Quotes để tránh lỗi xuống dòng) ---
    my_strains_data = [
        {
            "ID": "Strain_01", 
            "Sequence": """MKNVKKRVGVVLLILAVLGVYMLAMPANTVSAAGVPFNTKYPYGPTSIADNQSEVTAMLKAEWEDWKSKRITSNGAGGYKRVQRDASTNYDTVSEGMGYGLLLAVCFNEQALFDDLYRYVKSHFNGNGLMHWHIDANNNVTSHDGGDGAATDADEDIALALIFADKLWGSSGAINYGQEARTLINNLYNHCVEHGSYVLKPGDRWGGSSVTNPSYFAPAWYKVYAQYTGDTRWNQVADKCYQIVEEVKKYNNGTGLVPDWCTASGTPASGQSYDYKYDATRYGWRTAVDYSWFGDQRAKANCDMLTKFFARDGAKGIVDGYTIQGSKISNNHNASFIGPVAAASMTGYDLNFAKELYRETVAVKDSEYYGYYGNSLRLLTLLYITGNFPNPLSDLSGQPTPPSNPTPSLPPQVVYGDVNGDGNVNSTDLTMLKRYLLKSVTNINREAADVNRDGAINSSDMTILKRYLIKSIPHLPY"""
        },
        {
            "ID": "Strain_02", 
            "Sequence": """MGDLERLQTSGTKIVGARTGSEIRLRGTCIGGWMNMENFINGFAGTDQGVRYALKEALGEAKAHFFFERMLDHFFGEADVRFLKESGFNCVRLPLNYRHFEDDEQPYVYKEEGFRRLDEALALCEKYGIYAILDLHAVQGFQNAHWHSDNSTRHSFFWHDATYQQRFYALWRAFAERYKDRSVVAGYNIMNEPCVNTPFGDYPHTFYANYKPDWERINRIYRKAVEEIRAVDPHHIIFLEGDMYSKLFTGLEAPFADNLVYSSHNYHAAGFGPGPYPGVIRSNNPNEPRGVYWDLEKQREAFRKHEGTVFTQKHQVPLWVGEFGSAYNGPAEEVADRLRSMDDQIRVFEENGAHWTTWTYKDVGIMGLVTLHPESEYMQRLSSFLEKKYRLGTDDWMHWLPAATARQQVAAMSAYLQETIDPSINPAFNKTALSQTVLCIYAATLLEPEYAKQFQGLPEEKLDDILQSFALEQCIVHRELHDIMRKHAGAR"""
        },
        {
            "ID": "Strain_03", 
            "Sequence": """MVVTFLFILGVVYGVKPWQEARAGSFNYGEALQKAIMFYEFQMSGKLPNWVRNNWRGDSALKDGQDNGLDLTGGWFDAGDHVKFNLPMSYTGTMLSWAAYEYKDAFVKSGQLEHILNQIEWVNDYFVKCHPSKYVYYYQVGDGGKDHAWWGPAEVMQMERPSFKVTQSSPGSAVVAETAASLAAASIVLKDRNPTKAATYLQHAKDLYEFAEVTKSDSGYTAANGYYNSWSGFYDELSWAAVWLYLATNDSTYLTKAESYVQNWPKISGSNIIDYKWAHCWDDVHNGAALLLAKITDKDTYKQIIESHLDYWTTGYNGERIKYTPKGLAWLDQWGSLRYATTTAFLAFVYSDWSGCPTGKKETYRKFGESQIDYALGSTGRSFVVGFGTNPPKRPHHRTAHSSWADSQSIPSYHRHTLYGALVGGPGSDDSYTDDISNYVNNEVACDYNAGFVGALAKMYLLYGGNPIPDFKAIETPTNDEFFVEAGINASGTNFIEIKAIVNNQSGWPARATNKLKFRYFVDLSELIKAGYSPNQLTLSTNYNQGAKVSGPYVWDSSRNIYYILVDFTGTLIYPGGQDKYKKEVQFRIAAPQNVQWDNSNDYSFQDIKGVSSGSVVKTKYIPLYDEDIKVWGEEPGTSGVSPTPTASVTPTPTPTPTATPTPTPTPTVTPTPTVTATPTPTPTPTSTPTVTPTPTPVSTPATSGQIKVLYANKETNSTTNTIRPWLKVVNSGSSSIDLSRVTIRYWYTVDGERAQSAISDWAQIGASNVTFKFVKLSSSVSGADYYLEIGFKSGAGQLQPGKDTGEIQIRFNKDDWSNYNQGNDWSWIQSMTSYGENEKVTAYIDGVLVWGQEPSGTTPAPTSTPTVTVTPTPTPTPTVTPTPTVTATPTPTPTPTSTPVSTPATGGQIKVLYANKETNSTTNTIRPWLKVVNSGSSSIDLSRVTIRYWYTVDGERAQSAISDWAQIGASNVTFKFVKLSSSVSGADYYLEIGFKSGAGQLQPGKDTGEIQIRFNKDDWSNYNQGNDWSWIQSMTSYGENEKVTAYIDGVLVWGQEPSGATPAPTVTPTPTVTPTPTPAPTPTATPTPTPTPTVTPTPTVAPTPTPSSTPSGLGKYGQRFMWLWNKIHDPASGYFNQDGIPYHSVETLICEAPDYGHLTTSEAFSYYVWLEAVYGKLTGDWSKFKTAWDTLEKYMIPSAEDQPMRSYDPNKPATYAGEWETPDKYPSPLEFNVPVGKDPLHNELVSTYGSTLMYGMHWLMDVDNWYGYGKRGDGVSRASFINTFQRGPEESVWETVPHPSWEEFKWGGPNGFLDLFIKDQNYSKQWRYTNAPDADARAIQATYWAKVWAKEQGKFNEISSYVGKAAKMGDYLRYAMFDKYFKPLGCQDKNAAGGTGYDSAHYLLSWYYAWGGALDGAWSWKIGCSHAHFGYQNPMAAWALANDSDMKPKSPNGASDWAKSLKRQIEFYRWLQSAEGAIAGGATNSWNGRYEKYPAGTATFYGMAYEPNPVYRDPGSNTWFGFQAWSMQRVAEYYYVTGDKDAGTLLEKWVSWIKSVVKLNSDGTFAIPSTLDWSGQPDTWNGTYTGNPNLHVKVVDYGTDLGITASLANALLYYSAGTKKYGVFDEEAKNLAKELLDRMWKLYRDEKGLSAPEKRADYKRFFEQEVYIPAGWTGKMPNGDVIKSGVKFIDIRSKYKQDPDWPKLEAAYKSGQVPEFRYHRFWAQCDIAIVNATYEILFGNQ"""
        },
        {
            "ID": "Strain_04", 
            "Sequence": """GTTVTDCTPGPNQNGVTSVQGDEYRVQTNEWNSSAQQCLTINTATGAWTVSTANFSGGTGGAPATYPSIYKGCHWGNCTTKNVGMPIQISQIGSAVTSWSTTQVSSGAYDVAYDIWTNSTPTTTGQPNGTEIMIWLNSRGGVQPFGSQTATGVTVAGHTWNVWQGQQTSWKIISYVLTPGATSISNLDLKAIFADAAARGSLNTSDYLLDVEAGFEIWQGGQGLGSNSFSVSVTSGASHHHHHH"""
        },
        {
            "ID": "Strain_05", 
            "Sequence": """MSPRPLRALLGAAAAALVSAAALAFPSQAAANDSPFYVNPNMSSAEWVRNNPNDPRTPVIRDRIASVPQGTWFAHHNPGQITGQVDALMSAAQAAGKIPILVVYNAPGRDCGNHSSGGAPSHSAYRSWIDEFAAGLKNR PAYIIVEPDLISLMSSCMQHVQQEVLETMAYAGKALKAGSSQARIYFDAGHSAWHSPAQMASWLQQADISNSAHGIATNTSNYRWTADEVAYAKAVLSAIGNPSLRAVIDTSRNGNGPAGNEWCDPSGRAIGTPSTTNTGDPMIDAFLWIKLPGEADGCIAGAGQFVPQAAYEMAIAAGGTNPNPNPNPTPTPTPTPTPPPGSSGACTATYTIANEWNDGFQATVTVTANQNITGWTVTWTFTDGQTITNAWNADVSTSGSSVTARNVGHNGTLSQGASTEFGFVGSKGNSNSVPTLTCAAS"""
        }
    ]

    print(f"--- Đang phân tích {len(my_strains_data)} chủng thực nghiệm ---")
    results = []
    valid_aa = set("ACDEFGHIKLMNPQRSTVWY")

    for strain in my_strains_data:
        # Làm sạch: xóa bỏ dấu xuống dòng thực tế hoặc ký tự trắng dư thừa
        raw_seq = strain['Sequence'].replace("\n", "").replace(" ", "").upper()
        clean_seq = "".join([c for c in raw_seq if c in valid_aa])
        
        if len(clean_seq) < 50:
            print(f"⚠️ Trình tự {strain['ID']} quá ngắn, bỏ qua.")
            continue
            
        analysed = ProteinAnalysis(clean_seq)
        features = [[
            analysed.instability_index(),
            analysed.aromaticity(),
            analysed.isoelectric_point(),
            analysed.gravy()
        ]]
        
        prediction = model.predict(features)[0]
        prob = model.predict_proba(features)[0][1]
        
        results.append({
            "Strain_ID": strain['ID'],
            "Thermostable_Prob": f"{prob*100:.2f}%",
            "Result": "Thermophilic" if prediction == 1 else "Mesophilic"
        })

    df = pd.DataFrame(results)
    df.to_csv(output_csv, index=False)
    print("\n" + "="*50)
    print(df)
    print("="*50)
    print(f"✅ Đã lưu kết quả tại: {output_csv}")

if __name__ == "__main__":
    predict_my_strains('ai_training/gh5_thermo_model.pkl', 'ai_training/my_strains_final_predictions.csv')